[package]
name = "interop-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

#[profile.release]
#lto = true
#opt-level = 's'

[dependencies]
wasm-bindgen = "0.2"